name: Streamlit App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t face_rec1 -f Dockerfile .

      - name: Run Docker container
        run: docker run -d -p 8501:8501 face_rec1

      - name: Check Docker container status
        run: docker ps

      - name: Wait for Streamlit to start
        run: sleep 10

      - name: Access the Streamlit app
        run: curl -s -o /dev/null http://localhost:8501
